sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  ssh_known_hosts:
    - thecity.sfsu.edu
    - 111.22.33.44
before_install:
  - openssl aes-256-cbc -K $encrypted_dc1c0b2897bc_key -iv $encrypted_dc1c0b2897bc_iv -in deploy_rsa.enc -out deploy_rsa -d
script:
  - sh ./scripts/compile.sh
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: sh ./scripts/deploy.sh
    on:
      branch: development